import { Doctor, Specialty } from './types';

export const SPECIALTIES: Specialty[] = [
  { id: 'general-physician', name: 'General Physician', icon: 'Stethoscope' },
  { id: 'dentist', name: 'Dentist', icon: 'Smile' },
  { id: 'cardiologist', name: 'Cardiologist', icon: 'HeartPulse' },
  { id: 'dermatologist', name: 'Dermatologist', icon: 'User' },
  { id: 'neurologist', name: 'Neurologist', icon: 'Brain' },
  { id: 'orthopedist', name: 'Orthopedist', icon: 'Bone' },
  { id: 'psychologist', name: 'Psychologist', icon: 'HeartHandshake' },
  { id: 'gynecologist', name: 'Gynecologist', icon: 'Baby' },
  { id: 'ent', name: 'ENT', icon: 'Ear' },
  { id: 'ophthalmologist', name: 'Ophthalmologist', icon: 'Eye' },
];

export const INSURANCE_PROVIDERS = ['Star Health', 'HDFC ERGO', 'ICICI Lombard', 'Niva Bupa', 'Care Health', 'Bajaj Allianz', 'Reliance General'];

export const DOCTORS: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Sarah Mitchell',
    specialty: 'Cardiologist',
    image: 'https://images.unsplash.com/photo-1559839734-2b71f1536783?q=80&w=300&h=300&auto=format&fit=crop',
    location: 'Kochi',
    clinicName: 'Aster Medcity',
    rating: 4.9,
    reviews: 124,
    experience: 12,
    fee: 800,
    availableSlots: ['10:00 AM', '11:30 AM', '02:00 PM', '04:00 PM'],
    about: 'Dr. Mitchell is a board-certified cardiologist specializing in interventional cardiology and heart health.',
    isVerified: true,
    languages: ['English', 'Malayalam', 'Hindi'],
    insuranceAccepted: ['Star Health', 'HDFC ERGO'],
    totalBookings: 1250,
    type: 'Clinic-based'
  },
  {
    id: '2',
    name: 'Dr. Ahmed Hassan',
    specialty: 'Dentist',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=300&h=300&auto=format&fit=crop',
    location: 'Calicut',
    clinicName: 'Starlight Dental Clinic',
    rating: 4.8,
    reviews: 210,
    experience: 10,
    fee: 500,
    availableSlots: ['09:00 AM', '10:00 AM', '01:00 PM', '03:00 PM'],
    about: 'Expert in cosmetic dentistry and orthodontics with a focus on painless treatments.',
    isVerified: true,
    languages: ['English', 'Malayalam'],
    insuranceAccepted: ['Star Health', 'Niva Bupa'],
    totalBookings: 3400,
    type: 'Clinic-based'
  },
  {
    id: '3',
    name: 'Dr. Emily Chen',
    specialty: 'Dermatologist',
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=300&h=300&auto=format&fit=crop',
    location: 'Thrissur',
    clinicName: 'DermaCare Skin Hospital',
    rating: 4.8,
    reviews: 89,
    experience: 8,
    fee: 600,
    availableSlots: ['11:00 AM', '02:00 PM', '04:30 PM'],
    about: 'Specialist in medical and aesthetic dermatology, helping you achieve healthy, radiant skin.',
    isVerified: true,
    languages: ['English', 'Malayalam'],
    insuranceAccepted: ['Care Health', 'ICICI Lombard'],
    totalBookings: 890,
    type: 'Clinic-based'
  },
  {
    id: '4',
    name: 'Dr. Michael Ross',
    specialty: 'General Physician',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&h=300&auto=format&fit=crop',
    location: 'Kannur',
    clinicName: 'Family Wellness Center',
    rating: 4.7,
    reviews: 56,
    experience: 15,
    fee: 400,
    availableSlots: ['08:00 AM', '10:30 AM', '01:30 PM'],
    about: 'Leading general physician focusing on preventive care and chronic disease management.',
    isVerified: true,
    languages: ['English', 'Malayalam', 'Hindi'],
    insuranceAccepted: ['Star Health', 'Niva Bupa'],
    totalBookings: 2100,
    type: 'Independent'
  }
];

export const LOCATIONS = [
  'Calicut',
  'Malappuram',
  'Thrissur',
  'Kochi',
  'Kannur'
];

export const TEAM_WHATSAPP_NUMBER = "+911234567890"; // Placeholder team number

export const TRANSLATIONS = {
  EN: {
    home: "Home",
    specialties: "Specialties",
    howToBook: "How to Book",
    forDoctors: "For Doctors",
    contact: "Contact",
    signIn: "Sign In",
    signUp: "Sign Up",
    heroTitle: "Book My Doctor",
    heroSubtitle: "Feel Better, Faster.",
    heroDesc: "Find the right doctor quickly and book with ease. Get instant SMS and WhatsApp confirmations.",
    findDoctor: "FIND DOCTOR",
    locating: "LOCATING...",
    selectCity: "Select City",
    searchPlaceholder: "Search by doctor or specialty",
    howToBookTitle: "How to Book",
    howToBookSubtitle: "3 Simple Steps to your healthcare.",
    step1Title: "Search for a doctor",
    step1Desc: "Browse verified profiles near you by specialty or location.",
    step2Title: "Choose Date & Time",
    step2Desc: "Select your preferred date and time from real-time slots.",
    step3Title: "Instant Booking",
    step3Desc: "Confirm your booking and receive instant SMS confirmation.",
    whyChooseTitle: "Why Choose BookMyDoctor?",
    whyChooseSubtitle: "Trusted by over 100,000 patients",
    verifiedDoctors: "Verified Doctors",
    instantBooking: "Instant Booking",
    zeroFees: "Zero Fees",
    patientFocused: "Patient Focused",
    forDoctorsTitle: "Are You a Clinic or Doctor?",
    forDoctorsDesc: "Join BookMyDoctor and receive new patients without marketing hassle. Simple dashboard. Easy appointment management. Zero setup cost.",
    registerClinic: "Register Clinic",
    joinIndividual: "Join as Individual Doctor",
    contactUs: "Contact Us",
    haveQuestions: "Have questions? We're here to help.",
    bookAppointment: "Book Appointment",
    patientInfo: "Patient Information",
    confirmBooking: "CONFIRM BOOKING",
    confirmed: "Confirmed!",
    checkPhone: "Check your phone for confirmation.",
    verifiedBooking: "Verified Booking",
    back: "BACK",
    continue: "CONTINUE",
    time: "Time",
    details: "Details",
    done: "Done",
    
    // Auth & Registration
    createAccount: "Create Account",
    imPatient: "I'm a Patient",
    findAndBook: "Find a doctor and book appointments instantly.",
    imDoctor: "I'm a Doctor",
    createProfile: "Create your profile and connect with new patients.",
    imClinicManager: "I'm a Clinic Manager",
    registerClinicDesc: "Register your clinic and manage your team of doctors.",
    alreadyHaveAccount: "Already have an account?",
    joinForEasyBooking: "Join us for easy booking and health management.",
    continueWithGoogle: "Continue with Google",
    continueWithApple: "Continue with Apple",
    orEmail: "OR WITH EMAIL",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    consentMsg: "I consent to data processing.",
    findOutMore: "Find out more",
    signUpForFree: "SIGN UP FOR FREE",
    byRegistering: "By registering, you agree to our",
    terms: "Terms",
    and: "and",
    privacyPolicy: "Privacy Policy",
    
    // Specialist Registration
    joinAsDoctor: "Join as a Doctor",
    joinAsDoctorDesc: "Create your profile, set your availability, and connect with new patients easily.",
    basicInfo: "Basic Info",
    licensing: "Licensing",
    account: "Account",
    agreement: "Agreement",
    approval: "Approval",
    firstName: "First Name",
    lastName: "Last Name",
    primarySpecialty: "Primary Specialty",
    generalPhysician: "General Physician",
    cardiologist: "Cardiologist",
    dermatologist: "Dermatologist",
    experienceYears: "Experience (Years)",
    createDoctorProfile: "CREATE DOCTOR PROFILE",
    uploadLicense: "Upload DHA/MOH License",
    uploadLicenseDesc: "PDF or JPG formats accepted. Maximum size 5MB.",
    chooseFile: "CHOOSE FILE",
    licenseNumber: "License Number",
    verifyLicense: "VERIFY LICENSE",
    workEmailAddress: "Work Email Address",
    contactPhone: "Contact Phone",
    securePassword: "Secure Password",
    platformTerms: "Platform Terms of Service",
    platformTermsDesc1: "By joining BookMyDoctor, you agree to provide accurate medical credentials and maintain an up-to-date availability schedule. Our platform acts as a bridge between patients and licensed professionals...",
    platformTermsDesc2: "Liability Disclosure: You acknowledge that medical advice provided via the platform is the sole responsibility of the practitioner. BookMyDoctor reserves the right to verify licenses with DHA/MOH at any time...",
    platformTermsDesc3: "Payment Terms: Subscription fees are billed monthly unless otherwise agreed upon. Commission on successful bookings is processed at the end of each cycle...",
    acceptTerms: "I accept the Platform Terms & Medical Liability Agreement",
    completeRegistration: "COMPLETE REGISTRATION",
    applicationReceived: "Application Received",
    applicationReceivedDesc: "Your profile is being activated. Our team is cross-referencing your DHA license with the national registry.",
    identityCheck: "Identity Check",
    completed: "COMPLETED",
    licenseValidation: "License Validation",
    inProgress: "IN PROGRESS",
    profileVisibility: "Profile Visibility",
    offline: "OFFLINE",
    visitMarketplace: "VISIT MARKETPLACE",
    whySpecialistsChooseUs: "Why Specialists Choose Us",
    targetedReach: "Targeted Reach",
    targetedReachDesc: "Patients searching for your specific specialty.",
    verifiedTrust: "Verified Trust",
    verifiedTrustDesc: "Build authority with patient reviews.",
    dhaCompliant: "DHA Compliant",
    dhaCompliantDesc: "100% compliant with UAE health regulations.",
    supportTeam: "Support Team",
    supportTeamDesc: "Need help with registration? Our onboarding specialists are here to assist.",
    chatWithSpecialistSupport: "Chat with Specialist Support",

    // Clinic Registration
    clinicInfo: "Clinic Info",
    adminAccount: "Admin Account",
    subscription: "Subscription",
    verification: "Verification",
    previousStep: "Previous Step",
    registerClinicFree: "Register Your Clinic – It’s Free",
    registerClinicFreeDesc: "Fill in your basic details and start receiving appointment requests today.",
    facilityName: "Facility Name",
    dhaLicenseNumber: "DHA License Number",
    city: "City",
    getStartedFree: "GET STARTED FREE",
    adminFullName: "Admin Full Name",
    workEmail: "Work Email",
    continueToDoctors: "CONTINUE TO DOCTORS",
    addYourDoctors: "Add Your Doctors",
    addYourDoctorsDesc: "You can add your primary specialists now or later.",
    noDoctorsAdded: "No doctors added yet",
    addFirstDoctor: "ADD FIRST DOCTOR",
    skipToSubscription: "SKIP TO SUBSCRIPTION",
    subscriptionPlan: "Subscription Plan",
    subscriptionPlanDesc: "Choose a package for your listing.",
    marketplacePlus: "Marketplace Plus",
    mostPopular: "Most Popular",
    unlimitedBookings: "Unlimited Bookings",
    whatsappConfirmations: "WhatsApp Confirmations",
    priorityInSearch: "Priority in Search",
    selectPlan: "SELECT PLAN",
    starter: "Starter",
    free3Months: "FREE (3 Months)",
    basicListing: "Basic Listing",
    smsConfirmations: "SMS Confirmations",
    noPriority: "No Priority",
    tryForFree: "TRY FOR FREE",
    alreadyHaveContract: "Already have a contract? Skip",
    reviewingLicense: "Reviewing License",
    reviewingLicenseDesc: "Our team is manually verifying your DHA/MOH license. We'll notify you via email within 24 hours.",
    verificationStatus: "Verification Status",
    pending: "PENDING",
    elevatePractice: "Elevate Your Practice's Digital Presence",
    monthlyVisitors: "50,000+ Monthly Visitors",
    monthlyVisitorsDesc: "Join the largest healthcare discovery platform in the UAE.",
    lowerNoShows: "85% Lower No-Shows",
    lowerNoShowsDesc: "Automated WhatsApp & SMS reminders keep your slots filled.",
    clinicsOnline: "+250 Clinics Online",
    clinicTestimonial: '"Switching to BookMyDoctor increased our patient bookings by 40% in just two months. The dashboard is incredibly intuitive."',
    clinicDirector: "Dr. Sarah, Clinic Director",
    healthArticles: "Health Articles",
    latestArticles: "Latest Articles",
    readMore: "Read More",
    verified: "Verified",
    doctors: "Doctors",
    chatWithOurTeam: "Chat with our Team",
    instantSupport: "Instant Support",
    whatsappSupport: "WhatsApp Support",
    bookingConfirmed: "Booking Confirmed!",
    bookingSuccessMsg: "Your appointment has been successfully scheduled. You will receive a confirmation message on your phone shortly.",
    backHome: "Back to Home",
    messageSent: "Message sent successfully!",
    howCanWeHelp: "How can we help you?",
    sendMessage: "Send Message",
    backToHome: "Back to Home",
    refineResults: "Refine Results",
    allRegions: "All Regions",
    specialty: "Specialty",
    allSpecialties: "All Specialties",
    type: "Type",
    allTypes: "All Types",
    independent: "Independent",
    clinicBased: "Clinic-based",
    clearFilters: "Clear Filters",
    showing: "Showing",
    topRated: "Top Rated",
    nearMe: "Near Me",
    lowestFee: "Lowest Fee",
    mostExperienced: "Most Experienced",
    findingDoctors: "Finding the best doctors for you...",
    alwaysFree: "Always Free",
    wereHereToHelp: "We're here to help.",
    supportLine: "Support Line",
    emailSupport: "Email Support",
    footerDesc: "Connecting you with the best healthcare professionals in your city. Fast, reliable, and always free.",
    forPatients: "For Patients",
    findADoctor: "Find a Doctor",
    askAnExpert: "Ask an Expert",
    listYourPractice: "List Your Practice",
    corporate: "Corporate",
    aboutUs: "About Us",
    adminAccess: "Admin Access",
    copyright: "© 2025 BookMyDoctor. All rights reserved.",
    askExpert: "Ask an Expert",
    aiAssistant: "HealthBuddy",
    resolveQueries: "Resolve your health queries with our specialists.",
    yourQuestion: "Your Question",
    sendQuestion: "Send Question",
    noSpecialists: "No specialists found",
    tryAdjusting: "Try adjusting your filters or search query.",
    availableTimes: "Available Times",
    book: "Book",
    now: "Now",
    healthInsights: "Health Insights",
    stayInformed: "Stay informed with the latest medical news and tips.",
    readArticle: "Read Article",
    welcomeBack: "Welcome Back",
    signInToManage: "Sign in to manage your appointments and health records.",
    loginAsSuperAdmin: "Login as SuperAdmin",
    signInAsDoctor: "Sign In as Doctor",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account?",
    registerNow: "Register Now",
    popularSpecialties: "Popular Specialties",
    worldClassCare: "World-class care across all medical fields.",
    selectSpecialty: "Select a specialty to find the right doctor.",
    partnerClinics: "Our Partner Clinics",
    topRatedFacilities: "Top-rated healthcare facilities in your city.",
    viewAllClinics: "View All Clinics",
    clinic: "Clinic",
  },
  HI: {
    home: "होम",
    specialties: "विशेषताएं",
    howToBook: "बुकिंग कैसे करें",
    forDoctors: "डॉक्टरों के लिए",
    contact: "संपर्क",
    signIn: "साइन इन",
    signUp: "साइन अप",
    heroTitle: "बुक माई डॉक्टर",
    heroSubtitle: "बेहतर महसूस करें, तेजी से।",
    heroDesc: "जल्दी से सही डॉक्टर खोजें और आसानी से बुक करें। तत्काल एसएमएस और व्हाट्सएप पुष्टिकरण प्राप्त करें।",
    findDoctor: "डॉक्टर खोजें",
    locating: "खोज रहे हैं...",
    selectCity: "शहर चुनें",
    searchPlaceholder: "डॉक्टर या विशेषता द्वारा खोजें",
    howToBookTitle: "बुकिंग कैसे करें",
    howToBookSubtitle: "आपके स्वास्थ्य देखभाल के लिए 3 सरल कदम।",
    step1Title: "डॉक्टर खोजें",
    step1Desc: "विशेषता या स्थान के आधार पर अपने पास सत्यापित प्रोफाइल ब्राउज़ करें।",
    step2Title: "तारीख और समय चुनें",
    step2Desc: "रीयल-टाइम स्लॉट से अपनी पसंदीदा तारीख और समय चुनें।",
    step3Title: "त्वरित बुकिंग",
    step3Desc: "अपनी बुकिंग की पुष्टि करें और तत्काल एसएमएस पुष्टिकरण प्राप्त करें।",
    whyChooseTitle: "बुक माई डॉक्टर क्यों चुनें?",
    whyChooseSubtitle: "100,000 से अधिक रोगियों द्वारा विश्वसनीय",
    verifiedDoctors: "सत्यापित डॉक्टर",
    instantBooking: "त्वरित बुकिंग",
    zeroFees: "शून्य शुल्क",
    patientFocused: "रोगी केंद्रित",
    forDoctorsTitle: "क्या आप क्लिनिक या डॉक्टर हैं?",
    forDoctorsDesc: "बुक माई डॉक्टर से जुड़ें और मार्केटिंग की परेशानी के बिना नए मरीज प्राप्त करें। सरल डैशबोर्ड। आसान नियुक्ति प्रबंधन। शून्य सेटअप लागत।",
    registerClinic: "क्लिनिक पंजीकृत करें",
    joinIndividual: "व्यक्तिगत डॉक्टर के रूप में जुड़ें",
    contactUs: "संपर्क करें",
    haveQuestions: "प्रश्न हैं? हम यहाँ मदद के लिए हैं।",
    bookAppointment: "अपॉइंटमेंट बुक करें",
    patientInfo: "रोगी की जानकारी",
    confirmBooking: "बुकिंग की पुष्टि करें",
    confirmed: "पुष्टि की गई!",
    checkPhone: "पुष्टिकरण के लिए अपना फोन चेक करें।",
    verifiedBooking: "सत्यापित बुकिंग",
    back: "पीछे",
    continue: "जारी रखें",
    time: "समय",
    details: "विवरण",
    done: "हो गया",
    
    // Auth & Registration
    createAccount: "खाता बनाएं",
    imPatient: "मैं एक मरीज हूँ",
    findAndBook: "डॉक्टर खोजें और तुरंत अपॉइंटमेंट बुक करें।",
    imDoctor: "मैं एक डॉक्टर हूँ",
    createProfile: "अपनी प्रोफाइल बनाएं और नए मरीजों से जुड़ें।",
    imClinicManager: "मैं एक क्लिनिक मैनेजर हूँ",
    registerClinicDesc: "अपने क्लिनिक को पंजीकृत करें और अपने डॉक्टरों की टीम का प्रबंधन करें।",
    alreadyHaveAccount: "पहले से ही एक खाता है?",
    joinForEasyBooking: "आसान बुकिंग और स्वास्थ्य प्रबंधन के लिए हमसे जुड़ें।",
    continueWithGoogle: "गूगल के साथ जारी रखें",
    continueWithApple: "एप्पल के साथ जारी रखें",
    orEmail: "या ईमेल के साथ",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    consentMsg: "मैं डेटा प्रोसेसिंग के लिए सहमत हूँ।",
    findOutMore: "अधिक जानें",
    signUpForFree: "मुफ्त में साइन अप करें",
    byRegistering: "पंजीकरण करके, आप हमारे",
    terms: "नियमों",
    and: "और",
    privacyPolicy: "गोपनीयता नीति",
    
    // Specialist Registration
    joinAsDoctor: "एक डॉक्टर के रूप में जुड़ें",
    joinAsDoctorDesc: "अपनी प्रोफाइल बनाएं, अपनी उपलब्धता सेट करें और नए मरीजों से आसानी से जुड़ें।",
    basicInfo: "बुनियादी जानकारी",
    licensing: "लाइसेंसिंग",
    account: "खाता",
    agreement: "समझौता",
    approval: "अनुमोदन",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    primarySpecialty: "प्राथमिक विशेषता",
    generalPhysician: "सामान्य चिकित्सक",
    cardiologist: "हृदय रोग विशेषज्ञ",
    dermatologist: "त्वचा रोग विशेषज्ञ",
    experienceYears: "अनुभव (वर्ष)",
    createDoctorProfile: "डॉक्टर प्रोफाइल बनाएं",
    uploadLicense: "DHA/MOH लाइसेंस अपलोड करें",
    uploadLicenseDesc: "PDF या JPG प्रारूप स्वीकार किए जाते हैं। अधिकतम आकार 5MB।",
    chooseFile: "फ़ाइल चुनें",
    licenseNumber: "लाइसेंस संख्या",
    verifyLicense: "लाइसेंस सत्यापित करें",
    workEmailAddress: "कार्य ईमेल पता",
    contactPhone: "संपर्क फोन",
    securePassword: "सुरक्षित पासवर्ड",
    platformTerms: "प्लेटफॉर्म सेवा की शर्तें",
    platformTermsDesc1: "BookMyDoctor में शामिल होकर, आप सटीक चिकित्सा क्रेडेंशियल प्रदान करने और अद्यतित उपलब्धता कार्यक्रम बनाए रखने के लिए सहमत होते हैं। हमारा प्लेटफॉर्म मरीजों और लाइसेंस प्राप्त पेशेवरों के बीच एक सेतु के रूप में कार्य करता है...",
    platformTermsDesc2: "देयता प्रकटीकरण: आप स्वीकार करते हैं कि प्लेटफॉर्म के माध्यम से प्रदान की गई चिकित्सा सलाह व्यवसायी की एकमात्र जिम्मेदारी है। BookMyDoctor किसी भी समय DHA/MOH के साथ लाइसेंस सत्यापित करने का अधिकार सुरक्षित रखता है...",
    platformTermsDesc3: "भुगतान शर्तें: सदस्यता शुल्क मासिक रूप से बिल किए जाते हैं जब तक कि अन्यथा सहमति न हो। सफल बुकिंग पर कमीशन प्रत्येक चक्र के अंत में संसाधित किया जाता है...",
    acceptTerms: "मैं प्लेटफॉर्म की शर्तों और चिकित्सा देयता समझौते को स्वीकार करता हूँ",
    completeRegistration: "पंजीकरण पूरा करें",
    applicationReceived: "आवेदन प्राप्त हुआ",
    applicationReceivedDesc: "आपकी प्रोफाइल सक्रिय की जा रही है। हमारी टीम राष्ट्रीय रजिस्ट्री के साथ आपके DHA लाइसेंस का मिलान कर रही है।",
    identityCheck: "पहचान की जांच",
    completed: "पूरा हुआ",
    licenseValidation: "लाइसेंस सत्यापन",
    inProgress: "प्रगति में",
    profileVisibility: "प्रोफाइल दृश्यता",
    offline: "ऑफलाइन",
    visitMarketplace: "मार्केटप्लेस देखें",
    whySpecialistsChooseUs: "विशेषज्ञ हमें क्यों चुनते हैं",
    targetedReach: "लक्षित पहुंच",
    targetedReachDesc: "मरीज आपकी विशिष्ट विशेषता की खोज कर रहे हैं।",
    verifiedTrust: "सत्यापित विश्वास",
    verifiedTrustDesc: "मरीजों की समीक्षाओं के साथ अधिकार बनाएं।",
    dhaCompliant: "DHA अनुपालन",
    dhaCompliantDesc: "यूएई स्वास्थ्य नियमों के साथ 100% अनुपालन।",
    supportTeam: "सहायता टीम",
    supportTeamDesc: "पंजीकरण में सहायता चाहिए? हमारे ऑनबोर्डिंग विशेषज्ञ सहायता के लिए यहां हैं।",
    chatWithSpecialistSupport: "विशेषज्ञ सहायता के साथ चैट करें",
    chatWithOurTeam: "हमारी टीम के साथ चैट करें",
    instantSupport: "त्वरित सहायता",
    whatsappSupport: "व्हाट्सएप सहायता",
    bookingConfirmed: "बुकिंग की पुष्टि हो गई!",
    bookingSuccessMsg: "आपका अपॉइंटमेंट सफलतापूर्वक निर्धारित कर दिया गया है। आपको जल्द ही अपने फोन पर एक पुष्टिकरण संदेश प्राप्त होगा।",
    backHome: "होम पर वापस जाएं",
    messageSent: "संदेश सफलतापूर्वक भेजा गया!",
    howCanWeHelp: "हम आपकी कैसे मदद कर सकते हैं?",
    sendMessage: "संदेश भेजें",
    backToHome: "होम पर वापस जाएं",
    refineResults: "परिणामों को परिष्कृत करें",
    city: "शहर",
    allRegions: "सभी क्षेत्र",
    specialty: "विशेषता",
    allSpecialties: "सभी विशेषताएं",
    type: "प्रकार",
    allTypes: "सभी प्रकार",
    independent: "स्वतंत्र",
    clinicBased: "क्लिनिक-आधारित",
    clearFilters: "फ़िल्टर साफ़ करें",
    showing: "दिखा रहे हैं",
    topRated: "टॉप रेटेड",
    nearMe: "मेरे पास",
    lowestFee: "सबसे कम शुल्क",
    mostExperienced: "सबसे अनुभवी",
    findingDoctors: "आपके लिए सबसे अच्छे डॉक्टरों की खोज कर रहे हैं...",
    alwaysFree: "हमेशा मुफ़्त",
    wereHereToHelp: "हम यहाँ मदद के लिए हैं।",
    supportLine: "सहायता लाइन",
    emailSupport: "ईमेल सहायता",
    footerDesc: "आपको अपने शहर के सर्वश्रेष्ठ स्वास्थ्य पेशेवरों से जोड़ना। तेज़, विश्वसनीय और हमेशा मुफ़्त।",
    forPatients: "मरीजों के लिए",
    findADoctor: "डॉक्टर खोजें",
    askAnExpert: "विशेषज्ञ से पूछें",
    listYourPractice: "अपना अभ्यास सूचीबद्ध करें",
    corporate: "कॉर्पोरेट",
    aboutUs: "हमारे बारे में",
    adminAccess: "एडमिन एक्सेस",
    copyright: "© 2025 BookMyDoctor. सर्वाधिकार सुरक्षित।",
    askExpert: "विशेषज्ञ से पूछें",
    aiAssistant: "हेल्थ बडी",
    resolveQueries: "हमारे विशेषज्ञों के साथ अपने स्वास्थ्य संबंधी प्रश्नों का समाधान करें।",
    yourQuestion: "आपका प्रश्न",
    sendQuestion: "प्रश्न भेजें",
    noSpecialists: "कोई विशेषज्ञ नहीं मिला",
    tryAdjusting: "अपने फ़िल्टर या खोज क्वेरी को समायोजित करने का प्रयास करें।",
    availableTimes: "उपलब्ध समय",
    book: "बुक करें",
    now: "अब",
    healthInsights: "स्वास्थ्य अंतर्दृष्टि",
    stayInformed: "नवीनतम चिकित्सा समाचारों और युक्तियों के साथ सूचित रहें।",
    readArticle: "लेख पढ़ें",
    welcomeBack: "वापसी पर स्वागत है",
    signInToManage: "अपनी नियुक्तियों और स्वास्थ्य रिकॉर्ड का प्रबंधन करने के लिए साइन इन करें।",
    loginAsSuperAdmin: "SuperAdmin के रूप में लॉगिन करें",
    signInAsDoctor: "डॉक्टर के रूप में साइन इन करें",
    forgotPassword: "पासवर्ड भूल गए?",
    noAccount: "खाता नहीं है?",
    registerNow: "अभी पंजीकरण करें",
    popularSpecialties: "लोकप्रिय विशेषताएं",
    worldClassCare: "सभी चिकित्सा क्षेत्रों में विश्व स्तरीय देखभाल।",
    selectSpecialty: "सही डॉक्टर खोजने के लिए एक विशेषता चुनें।",
    partnerClinics: "हमारे साथी क्लीनिक",
    topRatedFacilities: "आपके शहर में टॉप रेटेड स्वास्थ्य सुविधाएं।",
    viewAllClinics: "सभी क्लीनिक देखें",
    clinic: "क्लिनिक",

    // Clinic Registration
    clinicInfo: "क्लिनिक जानकारी",
    adminAccount: "एडमिन खाता",
    subscription: "सदस्यता",
    verification: "सत्यापन",
    previousStep: "पिछला चरण",
    registerClinicFree: "अपना क्लिनिक पंजीकृत करें - यह मुफ़्त है",
    registerClinicFreeDesc: "अपने बुनियादी विवरण भरें और आज ही अपॉइंटमेंट अनुरोध प्राप्त करना शुरू करें।",
    facilityName: "सुविधा का नाम",
    dhaLicenseNumber: "DHA लाइसेंस संख्या",
    getStartedFree: "मुफ्त में शुरू करें",
    adminFullName: "एडमिन का पूरा नाम",
    workEmail: "कार्य ईमेल",
    continueToDoctors: "डॉक्टरों के लिए जारी रखें",
    addYourDoctors: "अपने डॉक्टर जोड़ें",
    addYourDoctorsDesc: "आप अपने प्राथमिक विशेषज्ञों को अभी या बाद में जोड़ सकते हैं।",
    noDoctorsAdded: "अभी तक कोई डॉक्टर नहीं जोड़ा गया",
    addFirstDoctor: "पहला डॉक्टर जोड़ें",
    skipToSubscription: "सदस्यता पर जाएं",
    subscriptionPlan: "सदस्यता योजना",
    subscriptionPlanDesc: "अपनी लिस्टिंग के लिए एक पैकेज चुनें।",
    marketplacePlus: "मार्केटप्लेस प्लस",
    mostPopular: "सबसे लोकप्रिय",
    unlimitedBookings: "असीमित बुकिंग",
    whatsappConfirmations: "व्हाट्सएप पुष्टिकरण",
    priorityInSearch: "खोज में प्राथमिकता",
    selectPlan: "योजना चुनें",
    starter: "स्टार्टर",
    free3Months: "मुफ़्त (3 महीने)",
    basicListing: "बुनियादी लिस्टिंग",
    smsConfirmations: "SMS पुष्टिकरण",
    noPriority: "कोई प्राथमिकता नहीं",
    tryForFree: "मुफ्त में प्रयास करें",
    alreadyHaveContract: "पहले से ही एक अनुबंध है? छोड़ें",
    reviewingLicense: "लाइसेंस की समीक्षा",
    reviewingLicenseDesc: "हमारी टीम मैन्युअल रूप से आपके DHA/MOH लाइसेंस की पुष्टि कर रही है। हम आपको 24 घंटों के भीतर ईमेल के माध्यम से सूचित करेंगे।",
    verificationStatus: "सत्यापन स्थिति",
    pending: "लंबित",
    elevatePractice: "अपने अभ्यास की डिजिटल उपस्थिति बढ़ाएं",
    monthlyVisitors: "50,000+ मासिक आगंतुक",
    monthlyVisitorsDesc: "यूएई में सबसे बड़े स्वास्थ्य सेवा खोज मंच में शामिल हों।",
    lowerNoShows: "85% कम नो-शो",
    lowerNoShowsDesc: "स्वचालित व्हाट्सएप और एसएमएस अनुस्मारक आपके स्लॉट भरे रखते हैं।",
    clinicsOnline: "+250 क्लीनिक ऑनलाइन",
    clinicTestimonial: '"BookMyDoctor पर स्विच करने से केवल दो महीनों में हमारी मरीज बुकिंग में 40% की वृद्धि हुई। डैशबोर्ड अविश्वसनीय रूप से सहज है।',
    clinicDirector: "डॉ. सारा, क्लिनिक निदेशक",
    healthArticles: "स्वास्थ्य लेख",
    latestArticles: "नवीनतम लेख",
    readMore: "और पढ़ें",
    verified: "सत्यापित",
    doctors: "डॉक्टर",
  }
};
